### ISSUE TITLE
Error while doing session.create

### ISSUE THREAD

**Issue by anildigital** [cargomedia/janus-gateway-ruby#17]
```
irb(main):018:0> ws = JanusGateway::Transport::WebSocket.new('ws://localhost:8188/janus')
=> #<JanusGateway::Transport::WebSocket:0x007fb3bc11aab8 @url="ws://localhost:8188/janus", @protocol="janus-protocol", @client=nil, @transaction_queue={}>

irb(main):019:0> client = JanusGateway::Client.new(ws)
=> #<JanusGateway::Client:0x007fb3bb837658 @transport=#<JanusGateway::Transport::WebSocket:0x007fb3bc11aab8 @url="ws://localhost:8188/janus", @protocol="janus-protocol", @client=nil, @transaction_queue={}>, @options={:token=>nil, :admin_secret=>nil}>

irb(main):020:0> session = JanusGateway::Resource::Session.new(client)
=> #<JanusGateway::Resource::Session:0x007fb3bb827398 @heartbeat_thread=nil, @client=#<JanusGateway::Client:0x007fb3bb837658 @transport=#<JanusGateway::Transport::WebSocket:0x007fb3bc11aab8 @url="ws://localhost:8188/janus", @protocol="janus-protocol", @client=nil, @transaction_queue={}>, @options={:token=>nil, :admin_secret=>nil}>, @id=nil>

irb(main):021:0> session.create
NoMethodError: undefined method `{"janus":"create","transaction":"KVGWDOVPKXUDPSYWTBPJBPCG"}' for nil:NilClass
	from /Users/anil/.gem/ruby/2.3.2/gems/janus_gateway-0.0.14/lib/janus_gateway/transport/websocket.rb:67:in `send'
	from /Users/anil/.gem/ruby/2.3.2/gems/janus_gateway-0.0.14/lib/janus_gateway/transport/websocket.rb:77:in `send_transaction'
	from /Users/anil/.gem/ruby/2.3.2/gems/janus_gateway-0.0.14/lib/janus_gateway/client.rb:31:in `send_transaction'
	from /Users/anil/.gem/ruby/2.3.2/gems/janus_gateway-0.0.14/lib/janus_gateway/resource/session.rb:14:in `create'
	from (irb):21
	from /Users/anil/.rubies/ruby-2.3.2/bin/irb:11:in `<main>'

Anything obviously wrong?
```

**Comment by njam** [comment]
You stumbled upon a strange combination of incomplete documentation and a programming error where `session.create` doesn't check if the transport is already connected.
Both is fixed in https://github.com/cargomedia/janus-gateway-ruby/pull/18

Here's a more complete example to connect to a server and create a session:
```ruby
ws = JanusGateway::Transport::WebSocket.new('ws://localhost:8188/janus')
client = JanusGateway::Client.new(ws)
client.on(:open) { puts 'client connected' }
client.on(:close) { puts 'client disconnected' }

client.on(:open) do
  session = JanusGateway::Resource::Session.new(client)
  session.on(:create) { puts 'session created' }
  session.on(:destroy) { puts 'session destroyed' }
  session.create
end

client.run
```
